name: Terraform Multi-Scanner Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive || true

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend=false || true

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate || true

      - name: Run Checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          quiet: true
          soft_fail: true
          skip_check: CKV_AWS_18,CKV_AWS_144,CKV_AWS_145,CKV2_AWS_61,CKV2_AWS_62

      - name: Run KICS Scan
        continue-on-error: true
        uses: checkmarx/kics-github-action@v2.1.9
        with:
          path: terraform
          fail_on: none

      - name: Install Regula
        run: |
          curl -L -o regula.tar.gz https://github.com/fugue/regula/releases/latest/download/regula_Linux_x86_64.tar.gz
          tar -xzf regula.tar.gz
          chmod +x regula
          sudo mv regula /usr/local/bin/regula

      - name: Run Regula Scan
        continue-on-error: true
        run: regula run terraform || true

      - name: Pipeline Completed
        run: echo "Terraform multi-scanner pipeline completed."